import { Inter } from 'next/font/google';
import './globals.css';
import ReduxWrapper from './reduxProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#121212", color: "#fff" }}>
        <ReduxWrapper>{children}</ReduxWrapper>
      </body>
    </html>
  );
}
